export default [
    {
        id: "12",
        title: "Sunday night with Mahendra Singh Dhoni",
        price: 200,
        coverImg: "dhoni-cropped.jpg",
        stats: {
            rating: 4.9,
            reviewCount: 100,
        },
        location: "India",
        openSpots: 0,
    },
    {
        id: "13",
        title: "Cricket Lessons with Virat Kohli",
        price: 250,
        coverImg: "kohli-cropped.jpg",
        stats: {
            rating: 5.0,
            reviewCount: 80,
        },
        location: "Online",
        openSpots: 2,
    },
    {
        id: "14",
        title: "Football Master advice on improving foot movements in the game",
        price: 500,
        coverImg: "messi-cropped.jpg",
        stats: {
            rating: 5.0,
            reviewCount: 1000,
        },
        location: "Argentina",
        openSpots: 0,
    },

    {
        id: 67,
        title: "Real Life Lessons with Katie Zaferes. Here she talks on how she conquered swimming and became one of the best in the era",
        price: 136,
        coverImg: "katie-zaferes.png",
        stats: {
            rating: 5.0,
            reviewCount: 6,
        },
        location: "Online",
        openSpots: 1,
    },
    {
        id: 2,
        title: "Learn Wedding Photography with one of the most popular photographer in the world with the best camera",
        price: 125,
        coverImg: "wedding-photography.png",
        stats: {
            rating: 5.0,
            reviewCount: 30,
        },
        location: "Online",
        openSpots: 27,
    },
    {
        id: 3,
        title: "Group Mountain Biking. You are welcomed to bring your friends and go on a tour on a bicycle with gears",
        price: 50,
        coverImg: "mountain-bike.png",
        stats: {
            rating: 4.8,
            reviewCount: 2,
        },
        location: "Norway",
        openSpots: 3,
    },
    {
        id: "4",
        title: "Cricket Lessons with Virat Kohli",
        price: 250,
        coverImg: "kohli-cropped.jpg",
        stats: {
            rating: 5.0,
            reviewCount: 80,
        },
        location: "Online",
        openSpots: 1,
    },
    {
        id: "5",
        title: "Football Master advice on improving foot movements in the game",
        price: 500,
        coverImg: "messi-cropped.jpg",
        stats: {
            rating: 5.0,
            reviewCount: 1000,
        },
        location: "Argentina",
        openSpots: 0,
    },
    {
        id: "6",
        title: "Sunday night with Mahendra Singh Dhoni",
        price: 200,
        coverImg: "dhoni-cropped.jpg",
        stats: {
            rating: 4.9,
            reviewCount: 100,
        },
        location: "India",
        openSpots: 0,
    },
    {
        id: 90,
        title: "Real Life Lessons with Katie Zaferes. Here she talks on how she conquered swimming and became one of the best in the era",
        price: 136,
        coverImg: "katie-zaferes.png",
        stats: {
            rating: 5.0,
            reviewCount: 6,
        },
        location: "Online",
        openSpots: 1,
    },
    {
        id: 89,
        title: "Group Mountain Biking. You are welcomed to bring your friends and go on a tour on a bicycle with gears",
        price: 50,
        coverImg: "mountain-bike.png",
        stats: {
            rating: 4.8,
            reviewCount: 2,
        },
        location: "Norway",
        openSpots: 3,
    },
];
