# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # using npm will also use yarn
    directory: "/airbnb-experience" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm" # using npm will also use yarn
    directory: "/digital-card" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # using npm will also use yarn
    directory: "/meme-generator" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm" # using npm will also use yarn
    directory: "/react-facts" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm" # using npm will also use yarn
    directory: "/travel-journal" # Location of package manifests
    schedule:
      interval: "weekly"
      
